workspace(name = "ndn")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_rust",
    sha256 = "edb87c0d2ba70823fe3df7862676d695599314a4634b9758bd55f0e8f19c2751",
    urls = [
        "https://github.com/bazelbuild/rules_rust/releases/download/0.4.0/rules_rust-v0.4.0.tar.gz",
    ],
)
http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "61b24e273821a15146f9ae7577e64b53f6aa332d5a7056abe8221ae2c346fdbd",
    strip_prefix = "rules_nixpkgs-210d30a81cedde04b4281fd163428722278fddfb",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/210d30a81cedde04b4281fd163428722278fddfb.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("//toolchains:defs.bzl", "nixpkgs", "cc_toolchain", "rust_toolchain")
nixpkgs()
cc_toolchain()
rust_toolchain()
