name: "Example Project with Bazel 4"
on:
  pull_request:
  push:
jobs:
  full-build:
    name: build example_project_bzl_4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses:
          actions/checkout@v2.4.0
          # Flakes do not like shallow clones
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://github.com/patryk-kozak/disruptor/blob/master/nix-shell.sh
      - name: Build all
        run: cd example_project_bzl_4; bazel build //...
